# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://maxlenk.github.io/reliabulb.com" # the url of your github pages

# site information used in page title, meta data etc.
title: "Ron Lenk"
description: Invent. Design. Patent.

# color theme for links
theme-color: stone-600 # indigo|yellow|pink|green|stone|

# homepage information
author: Ron Lenk
author-image: reliabulb.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: Patents
  permalink: patents
- text: Economics
  permalink: economics
- text: Technology
  permalink: technology
- text: Contact
  permalink: contact

# use false to turn off any social media links
twitter: false
facebook: false
instagram: false
github: false
linkedin: https://www.linkedin.com/in/ron-lenk-a82b145/
medium: false
google-scholar: false
email: false

# footer information
footer-msg: false
footer-msg-link: false

# google analytics
google-analytics: false

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag

